[Rufus]
# ASTERIX OS v2.0 'Phantom' Automated Rufus Profile
# Preserves MBR/UEFI Hybrid Table and Configures Live Persistence
EnableUpdates = 0
CheckForUpdates = 0
Language = en-US
AdvancedOptions = 1
ListAllDrives = 0
BootType = 0
TargetSystem = 1
PartitionScheme = 0
PersistentPartitionSize = 4096
FileSystem = 0
ClusterSize = 4096
NewVolumeLabel = "ASTERIX_LIVE"
QuickFormat = 1
