[Rufus]
# ASTERIX OS v2.0 'Phantom' Dual-Boot Automation Profile
EnableUpdates = 0
CheckForUpdates = 0
Language = en-US
AdvancedOptions = 1
ListAllDrives = 0
BootType = 0
# Target Architecture: Dual UEFI (GPT) & Legacy BIOS (MBR)
TargetSystem = 1
PartitionScheme = 0
PersistentPartitionSize = 8192
FileSystem = 0
ClusterSize = 4096
NewVolumeLabel = "ASTERIX_LIVE"
QuickFormat = 1
